sudo: required
services:
  - docker
before_install:
  - docker build -t verifyiscloudready/firstrepo:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push verifyiscloudready/firstrepo:v1.0
notifications:
  email:
    recipients:
      - verifyiscloudready@gmail.com
    on_success: always
    on_failure: always
